name: Pipeline

on: [ push, pull_request ]

jobs:
  build:
    name: Build application resource
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Installing and compiling resource
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build

      - name: Archive builded resource
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            dist/
            fxmanifest.lua
            package.json
            package-lock.json